### ISSUE TITLE
Error with current master

### ISSUE THREAD

**Issue by pcav** [geometalab/ArcGISConnector-QGIS-Plugin#10]
Might be a plugin issue, or not.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paolo/.qgis2/python/plugins/ArcGISConnectorQGISPlugin/**init**.py", line 27, in classFactory
    from connector import Connector
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.qgis2/python/plugins/ArcGISConnectorQGISPlugin/connector.py", line 38, in 
    import requests
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.qgis2/python/plugins/ArcGISConnectorQGISPlugin/requests/__init__.py", line 53, in 
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.qgis2/python/plugins/ArcGISConnectorQGISPlugin/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in 
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by sfkeller** [comment]
Solved in new release?
